### PR TITLE
Create yelp API file

### PR DESCRIPTION
**Pull request by alicia-mctc**
@mn4774jm  can you check this.  I created the file and could not get it to run.  Thanks.

### CODE REVIEW

**Comment by mn4774jm** [comment]
Couple of issues here before we can look to merge.
1) your feedback variable is not reaching the rest of your program as it is inside of your get_user_feedback function and not being passed to anything. You will need to create other modular functions for the other aspects of the program.
2) Your syntax for your headers is a little off. It currently reads "headers = {'Authorization': 'Bearer' + YELP_API_KEY}".
What you are looking for is "headers = {'Authorization': 'Bearer %s' % YELP_API_KEY}.

**Comment by mn4774jm** [comment]
Hey Alicia,
I left a comment in git with the solution to your issues. Correct those and we can look at merging. In addition, could you please make sure to post pull requests to the slack so Clara can see it? Thanks!

**Comment by alicia-mctc** [comment]
Thank you.
________________________________

**Comment by mn4774jm** [comment]
I also noticed that you have ''response = requests.get(yelp_url, headers=headers, params=parameters).json(0)" in your code. Remove the '0' from the .json() argument.

**Comment by alicia-mctc** [comment]
I have trouble viewing your solutions.  Where in Git?
________________________________

**Comment by mn4774jm** [comment]
I didn’t change any of you code. I just added comments to your pull request at https://github.com/mn4774jm/wishful_travel_app/pull/18

**Comment by claraj** [comment]
Couple of comments and suggestions @alicia-mctc  https://gist.github.com/claraj/c90b5c41290e4ad3b52b70ace1cedb1d

**Comment by claraj** [comment]
API call working. Next thing is to decide - discuss with team - what format/structure the data should be returned. What format would be useful for the rest of the app?

Once that's decided and implemented, this branch could be merged so the rest of the app can incorporate Yelp API calls - but don't forget to come back and add error handling and tests.

**Comment by mn4774jm** [comment]
Almost there.
1) the get_restaurants_for_location function will need to accept location and term in its parameters on line 16. Term in the API is a user submitted string that will include things like, pizza, sushi, etc. 
2) You query_params also will need to be tweaked a little bit. 'term' needs to accept the parameter that was passed to the function on line 16, location is fine. You will also need to add a couple more params including 'categories': 'restaurants'.
The end result will look something like this: query_params = {'term': search_term, 'categories': category, 'location': location, 'radius': 10000, 'price': price, 'limit': 20}
3) Your conditional validation on lines 21-24 doesn't seem to be doing anything
4) Error handling will need to be added eventually for the requests.get() bit of the program
5) for the return we will need you to return the restaurants variable that you created on line 31.

Otherwise it is just doing some clean-up of the code you were using to print the output, since that won't be used when merged to the master branch.

Let me know if you want to do a zoom at some point today to go over any of this.

**Comment by mn4774jm** [comment]
API is functional. Will need to make sure that environment variable for other people works. Otherwise, it will be exception handling and cleaning up errant comments.

**Comment by alicia-mctc** [comment]
Many thanks.
________________________________

**Pull request merged**
